<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title>Welcome to the StringTemplate ViewEngine Demo</title>
    <link href="/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="container">
        <h1>StringTemplate View Engine for ASP.Net MVC</h1>
        <div id="menu">$shared/menu()$</div>
        <div id="left">
            $left$
        </div>
        <div id="right">
            $right$
        </div>
    </div>
</body>
</html>
